import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="" href="" />
      </Head>
      <main>
        <Header/>
      </main>
    </>
  )
}
export default Home
